name: flutter_mosaic
description: 'Easy mosaic effect for Flutter, add a mosaic effect to any widget.'
version: 0.0.3
homepage: https://github.com/amoshuke/flutter_mosaic
repository: https://github.com/amoshuke/flutter_mosaic
issue_tracker: https://github.com/amoshuke/flutter_mosaic/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  shaders:
    - packages/flutter_mosaic/shaders/mosaic.frag

topics:
  - widget
  - shader
  - pixel
  - mosaic

screenshots:
  - description: 'Example Preview GIF'
    path: README/preview1.gif
