name: contributors
run-name: "Contributors"

on:
  push:
    branches:
      - main

jobs:
  contrib-readme-job:
    strategy:
      matrix:
        readme_path: [README.md, README-ZH.md]
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contribute List - ${{ matrix.readme_path }}
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          image_size: 100
          readme_path: ${{ matrix.readme_path }}
          use_username: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
