name: 'Deploy GitHub Pages'
run-name: 'Deploy GitHub Pages'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

# Disable permissions for all of the available permissions
permissions: {}

jobs:

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: 'stable'
      - name: Prepare dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Check Dart code formatting
        run: |
          dart format . -o none --set-exit-if-changed
      - name: Analyze Dart code
        run: |
          flutter analyze . --no-fatal-infos

  deploy:
    needs: [code-analysis]
    if: github.repository == 'AmosHuKe/flutter_mosaic'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: 'stable'
      - name: Prepare dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Build web (wasm)
        run: |
          cd example
          flutter build web --wasm --release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          branch: 'github-pages'
          folder: 'example/build/web'